# Generated by Django 6.0.6 on 2026-08-05 07:35

import referrals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default=referrals.models.generate_referral_code, max_length=20, unique=True),
        ),
    ]
