# Generated by Django 6.0.6 on 2026-08-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(blank=True, default='RyOx Express / Delhivery', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, help_text='Estimated Delivery Date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='AWB or Tracking Number', max_length=100, null=True),
        ),
    ]
