# Generated by Django 6.0.6 on 2026-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('him', 'Him'), ('her', 'Her'), ('unisex', 'Unisex'), ('gifting', 'Gifting')], default='unisex', max_length=10),
        ),
    ]
