# Generated by Django 6.0.6 on 2026-08-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.CharField(blank=True, help_text='e.g. Royal Amberwood, Bourbon Vanilla, Cedarwood', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.CharField(blank=True, help_text='e.g. Damask Rose, Jasmine Sambac, Lavender', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, help_text='e.g. Bergamot, Pink Pepper, Grapefruit', max_length=255),
        ),
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('top', 'Top Note'), ('heart', 'Heart Note'), ('base', 'Base Note')], default='top', max_length=10)),
                ('name', models.CharField(help_text='Note name e.g. Bergamot', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_notes', to='products.product')),
            ],
        ),
    ]
